# Generated by Django 5.2.12 on 2026-03-09 12:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
                ('cor', models.CharField(default='#ec5b13', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='marcas/')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('descricao', models.TextField()),
                ('tamanho_fralda', models.CharField(blank=True, choices=[('rn', 'RN'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG'), ('xg', 'XG')], max_length=10, null=True)),
                ('tamanho_roupa', models.CharField(blank=True, choices=[('rn', 'RN'), ('0_3m', '0-3m'), ('3_6m', '3-6m'), ('6_9m', '6-9m'), ('9_12m', '9-12m'), ('12_18m', '12-18m'), ('18_24m', '18-24m'), ('2t', '2 anos'), ('3t', '3 anos'), ('4t', '4 anos'), ('5t', '5 anos')], max_length=10, null=True)),
                ('cor', models.CharField(blank=True, max_length=50)),
                ('para_bebe', models.BooleanField(default=True)),
                ('para_mae', models.BooleanField(default=False)),
                ('genero', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('unisex', 'Unisex')], default='unisex', max_length=20)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('seminovo', 'Seminovo'), ('usado_otimo', 'Usado - Ótimo'), ('usado_bom', 'Usado - Bom'), ('usado_regular', 'Usado - Regular')], default='seminovo', max_length=20)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aceita_troca', models.BooleanField(default=True)),
                ('preferencias_troca', models.TextField(blank=True)),
                ('imagem_principal', models.ImageField(upload_to='produtos/')),
                ('imagem_2', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_3', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_4', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('imagem_5', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('mostrar_localizacao', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('em_troca', 'Em Troca'), ('trocado', 'Trocado'), ('indisponivel', 'Indisponível')], default='disponivel', max_length=20)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('favorito_count', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='baby.categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='baby.marca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baby.produto')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='baby.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropostaTroca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('produto_desejado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_como_desejo', to='baby.produto')),
                ('produto_oferecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_como_oferta', to='baby.produto')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to=settings.AUTH_USER_MODEL)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proposta de Troca',
                'verbose_name_plural': 'Propostas de Troca',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['status', 'criado_em'], name='baby_produt_status_31ce0a_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['categoria', 'status'], name='baby_produt_categor_40e6ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='produtofavorito',
            unique_together={('produto', 'usuario')},
        ),
    ]
