# Generated by Django 5.2.12 on 2026-03-17 23:30

import baby.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, upload_to='marcas/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), baby.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), baby.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_4',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), baby.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_5',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), baby.models.validar_tamanho_imagem]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_principal',
            field=models.ImageField(max_length=255, upload_to='produtos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), baby.models.validar_tamanho_imagem]),
        ),
    ]
